# Autogenerated by devscripts/update-version.py

__version__ = '2025.11.12.011616'

RELEASE_GIT_HEAD = '07cab85f875823d4f8e96c3133d3521bd615b7dd'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'fenom/yt-dlp'

ORIGIN = 'fenom/yt-dlp'

_pkg_version = '2025.11.12.011616'
