# Autogenerated by devscripts/update-version.py

__version__ = '2025.11.04.182119'

RELEASE_GIT_HEAD = '9ecf3d46a7152a2c7aecb5a4d7bb00c8d380572c'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'fenom/yt-dlp'

ORIGIN = 'fenom/yt-dlp'

_pkg_version = '2025.11.04.182119'
