# Autogenerated by devscripts/update-version.py

__version__ = '2025.08.23.172310'

RELEASE_GIT_HEAD = 'c53bcd5562cd3503f0fbe804705d6a74574d9ac2'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'fenom/yt-dlp'

ORIGIN = 'fenom/yt-dlp'

_pkg_version = '2025.08.23.172310'
